### ISSUE TITLE
Change Diagram in Readme to reflect updated functionality

### ISSUE THREAD

**Issue by nelsonic** [numo-labs/lambda-taggable-createDocument#13]
This lambda no longer writes to CloudSearch so this should be reflected in the diagram. relates to: https://github.com/numo-labs/lambda-taggable-createDocument/issues/12

**Comment by nelsonic** [comment]
![inspirational-search-taggable-system](https://cloud.githubusercontent.com/assets/194400/14984413/671c8938-113a-11e6-8b76-3af618041161.png)

@nikhilaravi please confirm this is ok. thanks.

**Comment by nikhilaravi** [comment]
@nelsonic looks great!
