### ISSUE TITLE
Taggable system diagram

### ISSUE THREAD

**Issue by nikhilaravi** [numo-labs/lambda-taggable-createDocument#5]
![inspirational-search-technical](https://cloud.githubusercontent.com/assets/5912647/14384190/8ca7489e-fd91-11e5-94e0-aea421945a1b.png)

**Comment by nelsonic** [comment]
![inspirational-search-taggable-system](https://cloud.githubusercontent.com/assets/194400/14984413/671c8938-113a-11e6-8b76-3af618041161.png)
https://github.com/numo-labs/lambda-taggable-createDocument/issues/13
